# Generated by Django 2.2.3 on 2019-07-26 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=100)),
                ('lastName', models.CharField(max_length=100)),
                ('nickName', models.CharField(max_length=50)),
                ('phoneNumber', models.CharField(max_length=10)),
                ('position', models.CharField(max_length=100)),
                ('create_at', models.CharField(max_length=100)),
                ('update_at', models.CharField(max_length=100)),
                ('leave', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('reason', models.CharField(max_length=100)),
                ('startDate', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=100)),
                ('endDate', models.CharField(max_length=100)),
                ('endTime', models.CharField(max_length=100)),
                ('create_at1', models.CharField(max_length=100)),
                ('update_at2', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Unpay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('startDate', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=100)),
                ('endDate', models.CharField(max_length=100)),
                ('endTime', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Sick',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('startDate', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=100)),
                ('endDate', models.CharField(max_length=100)),
                ('endTime', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='Annual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=100)),
                ('startDate', models.CharField(max_length=100)),
                ('startTime', models.CharField(max_length=100)),
                ('endDate', models.CharField(max_length=100)),
                ('endTime', models.CharField(max_length=100)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='employee.Employee')),
            ],
        ),
    ]
